# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: GMH BLOG
email: your-grimzmusichub@gmail.com
description: GMH is a platform set in place for the love of good music
#MUSICWORTHPAYINGFOR
baseurl: "/blog/" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "http://grimzmusichub.com"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter: grimzmusichub
facebook: grimzmusichub
google: grimzmusichub

